parameters:
#    php_ist_solr_work_shop.example.class: PhpIst\SolrWorkShopBundle\Example

services:
#    php_ist_solr_work_shop.example:
#        class: %php_ist_solr_work_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
